name: Build Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Publish to production branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          rm -rf production-build
          mkdir production-build

          cp -r dist/* production-build/

          cd production-build

          git init
          git checkout -b production

          git add .
          git commit -m "Deploy site"

          git remote add origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git
          git push --force origin production
